// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: api/sandhog/sandhog.proto

package sandhog

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A sandhog peer.
type SandhogPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIps []string `protobuf:"bytes,2,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	ListenPort int32    `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// Types that are assignable to Endpoint:
	//	*SandhogPeer_EndpointValue
	Endpoint isSandhogPeer_Endpoint `protobuf_oneof:"endpoint"`
	// Types that are assignable to PersistentKeepalive:
	//	*SandhogPeer_PersistentKeepaliveValue
	PersistentKeepalive isSandhogPeer_PersistentKeepalive `protobuf_oneof:"persistent_keepalive"`
}

func (x *SandhogPeer) Reset() {
	*x = SandhogPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandhogPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandhogPeer) ProtoMessage() {}

func (x *SandhogPeer) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandhogPeer.ProtoReflect.Descriptor instead.
func (*SandhogPeer) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{0}
}

func (x *SandhogPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SandhogPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *SandhogPeer) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (m *SandhogPeer) GetEndpoint() isSandhogPeer_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (x *SandhogPeer) GetEndpointValue() string {
	if x, ok := x.GetEndpoint().(*SandhogPeer_EndpointValue); ok {
		return x.EndpointValue
	}
	return ""
}

func (m *SandhogPeer) GetPersistentKeepalive() isSandhogPeer_PersistentKeepalive {
	if m != nil {
		return m.PersistentKeepalive
	}
	return nil
}

func (x *SandhogPeer) GetPersistentKeepaliveValue() int32 {
	if x, ok := x.GetPersistentKeepalive().(*SandhogPeer_PersistentKeepaliveValue); ok {
		return x.PersistentKeepaliveValue
	}
	return 0
}

type isSandhogPeer_Endpoint interface {
	isSandhogPeer_Endpoint()
}

type SandhogPeer_EndpointValue struct {
	EndpointValue string `protobuf:"bytes,4,opt,name=endpoint_value,json=endpointValue,proto3,oneof"`
}

func (*SandhogPeer_EndpointValue) isSandhogPeer_Endpoint() {}

type isSandhogPeer_PersistentKeepalive interface {
	isSandhogPeer_PersistentKeepalive()
}

type SandhogPeer_PersistentKeepaliveValue struct {
	PersistentKeepaliveValue int32 `protobuf:"varint,5,opt,name=persistent_keepalive_value,json=persistentKeepaliveValue,proto3,oneof"`
}

func (*SandhogPeer_PersistentKeepaliveValue) isSandhogPeer_PersistentKeepalive() {}

// Request a sandhog to create a new tunnel.
type StartTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Magic int32 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
}

func (x *StartTunnelRequest) Reset() {
	*x = StartTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelRequest) ProtoMessage() {}

func (x *StartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{1}
}

func (x *StartTunnelRequest) GetMagic() int32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

// A response from a sandhog that was requested to create a tunnel.
type StartTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{2}
}

func (x *StartTunnelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DigTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Magic int32        `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Peer  *SandhogPeer `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *DigTunnelRequest) Reset() {
	*x = DigTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DigTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigTunnelRequest) ProtoMessage() {}

func (x *DigTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigTunnelRequest.ProtoReflect.Descriptor instead.
func (*DigTunnelRequest) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{3}
}

func (x *DigTunnelRequest) GetMagic() int32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *DigTunnelRequest) GetPeer() *SandhogPeer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type DigTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Magic int32 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
}

func (x *DigTunnelResponse) Reset() {
	*x = DigTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DigTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigTunnelResponse) ProtoMessage() {}

func (x *DigTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigTunnelResponse.ProtoReflect.Descriptor instead.
func (*DigTunnelResponse) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{4}
}

func (x *DigTunnelResponse) GetMagic() int32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

type BuryTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuryTunnelRequest) Reset() {
	*x = BuryTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuryTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuryTunnelRequest) ProtoMessage() {}

func (x *BuryTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuryTunnelRequest.ProtoReflect.Descriptor instead.
func (*BuryTunnelRequest) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{5}
}

type BuryTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuryTunnelResponse) Reset() {
	*x = BuryTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuryTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuryTunnelResponse) ProtoMessage() {}

func (x *BuryTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuryTunnelResponse.ProtoReflect.Descriptor instead.
func (*BuryTunnelResponse) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{6}
}

var File_api_sandhog_sandhog_proto protoreflect.FileDescriptor

var file_api_sandhog_sandhog_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2f, 0x73, 0x61,
	0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x65, 0x6c,
	0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x22,
	0xfb, 0x01, 0x0a, 0x0b, 0x53, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x27, 0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x1a, 0x70, 0x65, 0x72,
	0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52,
	0x18, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61,
	0x6c, 0x69, 0x76, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x16, 0x0a, 0x14, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x2a, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x22, 0x25, 0x0a, 0x13, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0x5d, 0x0a, 0x10, 0x44, 0x69, 0x67, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x12, 0x33, 0x0a, 0x04, 0x70, 0x65,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74,
	0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x53, 0x61,
	0x6e, 0x64, 0x68, 0x6f, 0x67, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22,
	0x29, 0x0a, 0x11, 0x44, 0x69, 0x67, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x22, 0x13, 0x0a, 0x11, 0x42, 0x75,
	0x72, 0x79, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x14, 0x0a, 0x12, 0x42, 0x75, 0x72, 0x79, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa6, 0x02, 0x0a, 0x07, 0x53, 0x61, 0x6e, 0x64, 0x68, 0x6f,
	0x67, 0x12, 0x60, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x26, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74,
	0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x09, 0x44, 0x69, 0x67, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x24, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61,
	0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x44, 0x69, 0x67, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63,
	0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x44, 0x69, 0x67, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5d, 0x0a, 0x0a, 0x42, 0x75, 0x72, 0x79, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x2e,
	0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68,
	0x6f, 0x67, 0x2e, 0x42, 0x75, 0x72, 0x79, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69,
	0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x42, 0x75, 0x72, 0x79, 0x54, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x6c,
	0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x6e,
	0x64, 0x68, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sandhog_sandhog_proto_rawDescOnce sync.Once
	file_api_sandhog_sandhog_proto_rawDescData = file_api_sandhog_sandhog_proto_rawDesc
)

func file_api_sandhog_sandhog_proto_rawDescGZIP() []byte {
	file_api_sandhog_sandhog_proto_rawDescOnce.Do(func() {
		file_api_sandhog_sandhog_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sandhog_sandhog_proto_rawDescData)
	})
	return file_api_sandhog_sandhog_proto_rawDescData
}

var file_api_sandhog_sandhog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_sandhog_sandhog_proto_goTypes = []interface{}{
	(*SandhogPeer)(nil),         // 0: selftechio.sandhog.SandhogPeer
	(*StartTunnelRequest)(nil),  // 1: selftechio.sandhog.StartTunnelRequest
	(*StartTunnelResponse)(nil), // 2: selftechio.sandhog.StartTunnelResponse
	(*DigTunnelRequest)(nil),    // 3: selftechio.sandhog.DigTunnelRequest
	(*DigTunnelResponse)(nil),   // 4: selftechio.sandhog.DigTunnelResponse
	(*BuryTunnelRequest)(nil),   // 5: selftechio.sandhog.BuryTunnelRequest
	(*BuryTunnelResponse)(nil),  // 6: selftechio.sandhog.BuryTunnelResponse
}
var file_api_sandhog_sandhog_proto_depIdxs = []int32{
	0, // 0: selftechio.sandhog.DigTunnelRequest.peer:type_name -> selftechio.sandhog.SandhogPeer
	1, // 1: selftechio.sandhog.Sandhog.StartTunnel:input_type -> selftechio.sandhog.StartTunnelRequest
	3, // 2: selftechio.sandhog.Sandhog.DigTunnel:input_type -> selftechio.sandhog.DigTunnelRequest
	5, // 3: selftechio.sandhog.Sandhog.BuryTunnel:input_type -> selftechio.sandhog.BuryTunnelRequest
	2, // 4: selftechio.sandhog.Sandhog.StartTunnel:output_type -> selftechio.sandhog.StartTunnelResponse
	4, // 5: selftechio.sandhog.Sandhog.DigTunnel:output_type -> selftechio.sandhog.DigTunnelResponse
	6, // 6: selftechio.sandhog.Sandhog.BuryTunnel:output_type -> selftechio.sandhog.BuryTunnelResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_sandhog_sandhog_proto_init() }
func file_api_sandhog_sandhog_proto_init() {
	if File_api_sandhog_sandhog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sandhog_sandhog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandhogPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DigTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DigTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuryTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuryTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_sandhog_sandhog_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SandhogPeer_EndpointValue)(nil),
		(*SandhogPeer_PersistentKeepaliveValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sandhog_sandhog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sandhog_sandhog_proto_goTypes,
		DependencyIndexes: file_api_sandhog_sandhog_proto_depIdxs,
		MessageInfos:      file_api_sandhog_sandhog_proto_msgTypes,
	}.Build()
	File_api_sandhog_sandhog_proto = out.File
	file_api_sandhog_sandhog_proto_rawDesc = nil
	file_api_sandhog_sandhog_proto_goTypes = nil
	file_api_sandhog_sandhog_proto_depIdxs = nil
}
