// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: api/sandhog/sandhog.proto

package sandhog

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Result int32

const (
	Result_OK    Result = 0
	Result_NOTOK Result = 1
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "OK",
		1: "NOTOK",
	}
	Result_value = map[string]int32{
		"OK":    0,
		"NOTOK": 1,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sandhog_sandhog_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_api_sandhog_sandhog_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{0}
}

// A sandhog peer.
type SandhogPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIps []string `protobuf:"bytes,2,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	ListenPort int32    `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// Types that are assignable to Endpoint:
	//	*SandhogPeer_EndpointValue
	Endpoint isSandhogPeer_Endpoint `protobuf_oneof:"endpoint"`
	// Types that are assignable to PersistentKeepalive:
	//	*SandhogPeer_PersistentKeepaliveValue
	PersistentKeepalive isSandhogPeer_PersistentKeepalive `protobuf_oneof:"persistent_keepalive"`
}

func (x *SandhogPeer) Reset() {
	*x = SandhogPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandhogPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandhogPeer) ProtoMessage() {}

func (x *SandhogPeer) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandhogPeer.ProtoReflect.Descriptor instead.
func (*SandhogPeer) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{0}
}

func (x *SandhogPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SandhogPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *SandhogPeer) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (m *SandhogPeer) GetEndpoint() isSandhogPeer_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (x *SandhogPeer) GetEndpointValue() string {
	if x, ok := x.GetEndpoint().(*SandhogPeer_EndpointValue); ok {
		return x.EndpointValue
	}
	return ""
}

func (m *SandhogPeer) GetPersistentKeepalive() isSandhogPeer_PersistentKeepalive {
	if m != nil {
		return m.PersistentKeepalive
	}
	return nil
}

func (x *SandhogPeer) GetPersistentKeepaliveValue() int32 {
	if x, ok := x.GetPersistentKeepalive().(*SandhogPeer_PersistentKeepaliveValue); ok {
		return x.PersistentKeepaliveValue
	}
	return 0
}

type isSandhogPeer_Endpoint interface {
	isSandhogPeer_Endpoint()
}

type SandhogPeer_EndpointValue struct {
	EndpointValue string `protobuf:"bytes,4,opt,name=endpoint_value,json=endpointValue,proto3,oneof"`
}

func (*SandhogPeer_EndpointValue) isSandhogPeer_Endpoint() {}

type isSandhogPeer_PersistentKeepalive interface {
	isSandhogPeer_PersistentKeepalive()
}

type SandhogPeer_PersistentKeepaliveValue struct {
	PersistentKeepaliveValue int32 `protobuf:"varint,5,opt,name=persistent_keepalive_value,json=persistentKeepaliveValue,proto3,oneof"`
}

func (*SandhogPeer_PersistentKeepaliveValue) isSandhogPeer_PersistentKeepalive() {}

// Request a sandhog to create a new tunnel.
type StartTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the name of the tunnel
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the address of the tunnel
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` //
}

func (x *StartTunnelRequest) Reset() {
	*x = StartTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelRequest) ProtoMessage() {}

func (x *StartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{1}
}

func (x *StartTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartTunnelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// A response from a sandhog that was requested to create a tunnel.
type StartTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result Result `protobuf:"varint,1,opt,name=result,proto3,enum=selftechio.sandhog.Result" json:"result,omitempty"`
	// Types that are assignable to Tunnel:
	//	*StartTunnelResponse_TunnelSpecs
	Tunnel isStartTunnelResponse_Tunnel `protobuf_oneof:"tunnel"`
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sandhog_sandhog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sandhog_sandhog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_api_sandhog_sandhog_proto_rawDescGZIP(), []int{2}
}

func (x *StartTunnelResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_OK
}

func (m *StartTunnelResponse) GetTunnel() isStartTunnelResponse_Tunnel {
	if m != nil {
		return m.Tunnel
	}
	return nil
}

func (x *StartTunnelResponse) GetTunnelSpecs() *SandhogPeer {
	if x, ok := x.GetTunnel().(*StartTunnelResponse_TunnelSpecs); ok {
		return x.TunnelSpecs
	}
	return nil
}

type isStartTunnelResponse_Tunnel interface {
	isStartTunnelResponse_Tunnel()
}

type StartTunnelResponse_TunnelSpecs struct {
	TunnelSpecs *SandhogPeer `protobuf:"bytes,2,opt,name=tunnel_specs,json=tunnelSpecs,proto3,oneof"`
}

func (*StartTunnelResponse_TunnelSpecs) isStartTunnelResponse_Tunnel() {}

var File_api_sandhog_sandhog_proto protoreflect.FileDescriptor

var file_api_sandhog_sandhog_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2f, 0x73, 0x61,
	0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x65, 0x6c,
	0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x22,
	0xfb, 0x01, 0x0a, 0x0b, 0x53, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x27, 0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3e, 0x0a, 0x1a, 0x70, 0x65, 0x72,
	0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52,
	0x18, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61,
	0x6c, 0x69, 0x76, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x16, 0x0a, 0x14, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x42, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x99, 0x01, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x65, 0x6c, 0x66,
	0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x44, 0x0a,
	0x0c, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f,
	0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x53, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67,
	0x50, 0x65, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x70,
	0x65, 0x63, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2a, 0x1b, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x54, 0x4f, 0x4b, 0x10, 0x01, 0x32, 0x6b, 0x0a, 0x07, 0x53, 0x61,
	0x6e, 0x64, 0x68, 0x6f, 0x67, 0x12, 0x60, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x26, 0x2e, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69,
	0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73,
	0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f,
	0x67, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f,
	0x2f, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sandhog_sandhog_proto_rawDescOnce sync.Once
	file_api_sandhog_sandhog_proto_rawDescData = file_api_sandhog_sandhog_proto_rawDesc
)

func file_api_sandhog_sandhog_proto_rawDescGZIP() []byte {
	file_api_sandhog_sandhog_proto_rawDescOnce.Do(func() {
		file_api_sandhog_sandhog_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sandhog_sandhog_proto_rawDescData)
	})
	return file_api_sandhog_sandhog_proto_rawDescData
}

var file_api_sandhog_sandhog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sandhog_sandhog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_sandhog_sandhog_proto_goTypes = []interface{}{
	(Result)(0),                 // 0: selftechio.sandhog.Result
	(*SandhogPeer)(nil),         // 1: selftechio.sandhog.SandhogPeer
	(*StartTunnelRequest)(nil),  // 2: selftechio.sandhog.StartTunnelRequest
	(*StartTunnelResponse)(nil), // 3: selftechio.sandhog.StartTunnelResponse
}
var file_api_sandhog_sandhog_proto_depIdxs = []int32{
	0, // 0: selftechio.sandhog.StartTunnelResponse.result:type_name -> selftechio.sandhog.Result
	1, // 1: selftechio.sandhog.StartTunnelResponse.tunnel_specs:type_name -> selftechio.sandhog.SandhogPeer
	2, // 2: selftechio.sandhog.Sandhog.StartTunnel:input_type -> selftechio.sandhog.StartTunnelRequest
	3, // 3: selftechio.sandhog.Sandhog.StartTunnel:output_type -> selftechio.sandhog.StartTunnelResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_sandhog_sandhog_proto_init() }
func file_api_sandhog_sandhog_proto_init() {
	if File_api_sandhog_sandhog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sandhog_sandhog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandhogPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sandhog_sandhog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_sandhog_sandhog_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SandhogPeer_EndpointValue)(nil),
		(*SandhogPeer_PersistentKeepaliveValue)(nil),
	}
	file_api_sandhog_sandhog_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*StartTunnelResponse_TunnelSpecs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sandhog_sandhog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sandhog_sandhog_proto_goTypes,
		DependencyIndexes: file_api_sandhog_sandhog_proto_depIdxs,
		EnumInfos:         file_api_sandhog_sandhog_proto_enumTypes,
		MessageInfos:      file_api_sandhog_sandhog_proto_msgTypes,
	}.Build()
	File_api_sandhog_sandhog_proto = out.File
	file_api_sandhog_sandhog_proto_rawDesc = nil
	file_api_sandhog_sandhog_proto_goTypes = nil
	file_api_sandhog_sandhog_proto_depIdxs = nil
}
