// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: selftechio/naas/common.proto

package naas

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A request result.
type Result int32

const (
	Result_OK    Result = 0
	Result_NOTOK Result = 1
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "OK",
		1: "NOTOK",
	}
	Result_value = map[string]int32{
		"OK":    0,
		"NOTOK": 1,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_selftechio_naas_common_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_selftechio_naas_common_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_selftechio_naas_common_proto_rawDescGZIP(), []int{0}
}

// A request status.
type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result Result `protobuf:"varint,1,opt,name=result,proto3,enum=selftechio.naas.Result" json:"result,omitempty"`
	// Types that are assignable to Err:
	//	*Status_ErrMsg
	Err isStatus_Err `protobuf_oneof:"err"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_selftechio_naas_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_selftechio_naas_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_selftechio_naas_common_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_OK
}

func (m *Status) GetErr() isStatus_Err {
	if m != nil {
		return m.Err
	}
	return nil
}

func (x *Status) GetErrMsg() string {
	if x, ok := x.GetErr().(*Status_ErrMsg); ok {
		return x.ErrMsg
	}
	return ""
}

type isStatus_Err interface {
	isStatus_Err()
}

type Status_ErrMsg struct {
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3,oneof"`
}

func (*Status_ErrMsg) isStatus_Err() {}

var File_selftechio_naas_common_proto protoreflect.FileDescriptor

var file_selftechio_naas_common_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2f, 0x6e, 0x61, 0x61,
	0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x61, 0x73, 0x22,
	0x5b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x6c, 0x66,
	0x74, 0x65, 0x63, 0x68, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x61, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x65, 0x72,
	0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x2a, 0x1b, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x4e, 0x4f, 0x54, 0x4f, 0x4b, 0x10, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x6c, 0x66, 0x74, 0x65, 0x63, 0x68,
	0x69, 0x6f, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x68, 0x6f, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x61, 0x61, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_selftechio_naas_common_proto_rawDescOnce sync.Once
	file_selftechio_naas_common_proto_rawDescData = file_selftechio_naas_common_proto_rawDesc
)

func file_selftechio_naas_common_proto_rawDescGZIP() []byte {
	file_selftechio_naas_common_proto_rawDescOnce.Do(func() {
		file_selftechio_naas_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_selftechio_naas_common_proto_rawDescData)
	})
	return file_selftechio_naas_common_proto_rawDescData
}

var file_selftechio_naas_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_selftechio_naas_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_selftechio_naas_common_proto_goTypes = []interface{}{
	(Result)(0),    // 0: selftechio.naas.Result
	(*Status)(nil), // 1: selftechio.naas.Status
}
var file_selftechio_naas_common_proto_depIdxs = []int32{
	0, // 0: selftechio.naas.Status.result:type_name -> selftechio.naas.Result
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_selftechio_naas_common_proto_init() }
func file_selftechio_naas_common_proto_init() {
	if File_selftechio_naas_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_selftechio_naas_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_selftechio_naas_common_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Status_ErrMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_selftechio_naas_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_selftechio_naas_common_proto_goTypes,
		DependencyIndexes: file_selftechio_naas_common_proto_depIdxs,
		EnumInfos:         file_selftechio_naas_common_proto_enumTypes,
		MessageInfos:      file_selftechio_naas_common_proto_msgTypes,
	}.Build()
	File_selftechio_naas_common_proto = out.File
	file_selftechio_naas_common_proto_rawDesc = nil
	file_selftechio_naas_common_proto_goTypes = nil
	file_selftechio_naas_common_proto_depIdxs = nil
}
